# Generated by Django 3.1.7 on 2021-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'default_related_name': 'appointments', 'ordering': ('-created',), 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'default_related_name': 'clients', 'ordering': ('-created',), 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='profile',
        ),
    ]
